
format_version: 10
pipelines:
  prometheus-tf-apply:
    group: Tools
    materials:
      git-da613e5:
        git: https://github.com/raju-b71/tools-automation-code.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - ansible:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            ansible:
              tasks:
                - exec: { command: ansible-playbook, arguments: [ "-i", "prometheus.rajdevops.online,", "tools.yml", "-e", "tool_name=prometheus", "-e", "ansible_user=ec2-user", "-e", "ansible_pass=DevOps321" ], run_if: passed }
